_wandb:
    value:
        cli_version: 0.25.1
        e:
            notkxc7hrcy5edfhx53ep6j3hh6ysvav:
                codePath: yolo_training.py
                codePathLocal: yolo_training.py
                cpu_count: 12
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1000186310656"
                        used: "222460555264"
                email: johnzhou.engineer@gmail.com
                executable: C:\Users\john2\anaconda3\python.exe
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-37607ac6-b440-6c4b-2efa-778194f53120
                host: John-desktop
                memory:
                    total: "34105610240"
                os: Windows-11-10.0.26200-SP0
                program: D:\617 project\yolo_training.py
                python: CPython 3.13.5
                root: D:\617 project
                startedAt: "2026-03-27T10:10:24.241225Z"
                writerId: notkxc7hrcy5edfhx53ep6j3hh6ysvav
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.5
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
batch:
    value: 16
epochs:
    value: 50
imgsz:
    value: 640
model:
    value: yolov8s.pt
